<?php
$jobs = array(
  1000 =>'Noblesse',
  1100 =>'Dawn Warrior',
  1110 =>'Dawn Warrior 2',
  1111 =>'Dawn Warrior 3',
  1200 =>'Blaze Wizard',
  1200 =>'Blaze Wizard',
  1210 =>'Blaze Wizard 2',
  1211 =>'Blaze Wizard 3',
  1300 =>'Wind Archer',
  1310 =>'Wind Archer 2',
  1311 =>'Wind Archer 3',
  1400 =>'Night Walker',
  1410 =>'Night Walker 2',
  1411 =>'Night Walker 3',
  1500 =>'Thunder Breaker',
  1510 =>'Thunder Breaker 2',
  1511 =>'Thunder Breaker 3',
  2000 =>'Legend',
  2100 =>'Aran 1',
  2110 =>'Aran 2',
  2111 =>'Aran3',
  2112 =>'Aran 4',
  900 =>'GameMaster',
  910 =>'Super GM',
  500 =>'Pirate',
  510 =>'Brawler',
  520 =>'Gunslinger',
  511 =>'Marauder',
  521 =>'Outlaw',
  512 =>'Buccaneer',
  522 =>'Corsair',
  0   =>'Beginner',
  100 =>'Warrior',
  110 =>'Fighter',
  120 =>'Page',
  130 =>'Spearman',
  111 =>'Crusader',
  121 =>'White Knight',
  131 =>'Dragon Knight',
  112 =>'Hero',
  122 =>'Paladin',
  132 =>'Dark Knight',
  200 =>'Magician',
  210 =>'Fire/Poison Wizard',
  220 =>'Ice/Lightning Wizard',
  230 =>'Cleric',
  211 =>'Fire/Poison Mage',
  221 =>'Ice/Lightning Mage',
  231 =>'Priest',
  212 =>'Fire/Poison Arch Mage',
  222 =>'Ice/Lightning Arch Mage',
  232 =>'Bishop',
  300 =>'Bowman',
  310 =>'Hunter',
  320 =>'Crossbowman',
  311 =>'Ranger',
  321 =>'Sniper',
  312 =>'Bow Master',
  322 =>'Crossbow Master',
  400 =>'Thief',
  410 =>'Assassin',
  420 =>'Bandit',
  411 =>'Hermit',
  421 =>'Chief Bandit',
  412 =>'Nights Lord',
  422 =>'Shadower',
  430 =>'Blade Reqruit',
  431 =>'Blade Acolyte',
  432 =>'Blade Specialist',
  433 =>'Blade Lord',
  2001 =>'Farmer',
  2200 =>'Evan',
  2210 =>'Evan',
  2211 =>'Evan',
  2212 =>'Evan',
  2213 =>'Evan',
  2214 =>'Evan',
  2215 =>'Evan',
  2216 =>'Evan',
  2217 =>'Evan',
  2218 =>'Evan',
  3000 =>'Citizen',
  3200 =>'Battle Mage',
  3210 =>'Battle Mage',
  3211 =>'Battle Mage',
  3212 =>'Battle Mage',
  3300 =>'Wild Hunter',
  3310 =>'Wild Hunter',
  3311 =>'Wild Hunter',
  3312 =>'Wild Hunter',
  3500 =>'Mechanic',
  3510 =>'Mechanic',
  3511 =>'Mechanic',
  3512 =>'Mechanic',
  501 =>'Pitate (Cannoneer)',
  530 =>'Cannoneer',
  531 =>'Cannon Trooper',
  532 =>'Cannon Trooper',
  2002 =>'Elf',
  2300 =>'Mercedes',
  2310 =>'Mercedes',
  2311 =>'Mercedes',
  2312 =>'Mercedes',
  3001 =>'Citizen (Demon Slyaer)',
  3100 =>'DemonSlyaer',
  3110 =>'DemonSlyaer',
  3111 =>'DemonSlyaer',
  3112 =>'DemonSlyaer',
  508 =>'Jett',
  570 =>'Jett',
  571 =>'Jett',
  572 =>'Jett',
  2003 =>'Miser (Phantom)',
  2400 =>'Phantom',
  2410 =>'Phantom',
  2411 =>'Phantom',
  2412 =>'Phantom'
);

$job = array(
  1000 =>'<img src="./images/rank/noblesse.png">',
  1100 =>'<img src="./images/rank/warrior.png">',
  1110 =>'<img src="./images/rank/warrior.png">',
  1111 =>'<img src="./images/rank/warrior.png">',
  1200 =>'<img src="./images/rank/mage.png">',
  1200 =>'<img src="./images/rank/mage.png">',
  1210 =>'<img src="./images/rank/mage.png">',
  1211 =>'<img src="./images/rank/mage.png">',
  1300 =>'<img src="./images/rank/archer.png">',
  1310 =>'<img src="./images/rank/archer.png">',
  1311 =>'<img src="./images/rank/archer.png">',
  1400 =>'<img src="./images/rank/thief.png">',
  1410 =>'<img src="./images/rank/thief.png">',
  1411 =>'<img src="./images/rank/thief.png">',
  1500 =>'<img src="./images/rank/pirate.png">',
  1510 =>'<img src="./images/rank/pirate.png">',
  1511 =>'<img src="./images/rank/pirate.png">',
  2000 =>'<img src="./images/rank/rank_job5.gif">',
  2100 =>'<img src="./images/rank/rank_job5.gif">',
  2110 =>'<img src="./images/rank/rank_job5.gif">',
  2111 =>'<img src="./images/rank/rank_job5.gif">',
  2112 =>'<img src="./images/rank/rank_job5.gif">',
  900 =>'<img src="./images/rank/rank_job5.gif">',
  910 =>'<img src="./images/rank/rank_job5.gif">',
  500 =>'<img src="./images/rank/rank_job6.png">',
  510 =>'<img src="./images/rank/rank_job6.png">',
  520 =>'<img src="./images/rank/rank_job6.png">',
  511 =>'<img src="./images/rank/rank_job6.png">',
  521 =>'<img src="./images/rank/rank_job6.png">',
  512 =>'<img src="./images/rank/rank_job6.png">',
  522 =>'<img src="./images/rank/rank_job6.png">',
  0   =>'<img src="./images/rank/rank_job0.gif">',
  100 =>'<img src="./images/rank/rank_job1.gif">',
  110 =>'<img src="./images/rank/rank_job1.gif">',
  120 =>'<img src="./images/rank/rank_job1.gif">',
  130 =>'<img src="./images/rank/rank_job1.gif">',
  111 =>'<img src="./images/rank/rank_job1.gif">',
  121 =>'<img src="./images/rank/rank_job1.gif">',
  131 =>'<img src="./images/rank/rank_job1.gif">',
  112 =>'<img src="./images/rank/rank_job1.gif">',
  122 =>'<img src="./images/rank/rank_job1.gif">',
  132 =>'<img src="./images/rank/rank_job1.gif">',
  200 =>'<img src="./images/rank/rank_job2.gif">',
  210 =>'<img src="./images/rank/rank_job2.gif">',
  220 =>'<img src="./images/rank/rank_job2.gif">',
  230 =>'<img src="./images/rank/rank_job2.gif">',
  211 =>'<img src="./images/rank/rank_job2.gif">',
  221 =>'<img src="./images/rank/rank_job2.gif">',
  231 =>'<img src="./images/rank/rank_job2.gif">',
  212 =>'<img src="./images/rank/rank_job2.gif">',
  222 =>'<img src="./images/rank/rank_job2.gif">',
  232 =>'<img src="./images/rank/rank_job2.gif">',
  300 =>'<img src="./images/rank/rank_job3.gif">',
  310 =>'<img src="./images/rank/rank_job3.gif">',
  320 =>'<img src="./images/rank/rank_job3.gif">',
  311 =>'<img src="./images/rank/rank_job3.gif">',
  321 =>'<img src="./images/rank/rank_job3.gif">',
  312 =>'<img src="./images/rank/rank_job3.gif">',
  322 =>'<img src="./images/rank/rank_job3.gif">',
  400 =>'<img src="./images/rank/rank_job4.gif">',
  410 =>'<img src="./images/rank/rank_job4.gif">',
  420 =>'<img src="./images/rank/rank_job4.gif">',
  411 =>'<img src="./images/rank/rank_job4.gif">',
  421 =>'<img src="./images/rank/rank_job4.gif">',
  412 =>'<img src="./images/rank/rank_job4.gif">',
  422 =>'<img src="./images/rank/rank_job4.gif">',
  430 =>'<img src="./images/rank/DualBlade.png">',
  431 =>'<img src="./images/rank/DualBlade.png">',
  432 =>'<img src="./images/rank/DualBlade.png">',
  433 =>'<img src="./images/rank/DualBlade.png">',
  2001 =>'<img src="./images/rank/Evan.png">',
  2200 =>'<img src="./images/rank/Evan.png">',
  2210 =>'<img src="./images/rank/Evan.png">',
  2211 =>'<img src="./images/rank/Evan.png">',
  2212 =>'<img src="./images/rank/Evan.png">',
  2213 =>'<img src="./images/rank/Evan.png">',
  2214 =>'<img src="./images/rank/Evan.png">',
  2215 =>'<img src="./images/rank/Evan.png">',
  2216 =>'<img src="./images/rank/Evan.png">',
  2217 =>'<img src="./images/rank/Evan.png">',
  2218 =>'<img src="./images/rank/Evan.png">',
  3000 =>'<img src="./images/rank/rank_job0.gif">',
  3200 =>'<img src="./images/rank/BattleMage.png">',
  3210 =>'<img src="./images/rank/BattleMage.png">',
  3211 =>'<img src="./images/rank/BattleMage.png">',
  3212 =>'<img src="./images/rank/BattleMage.png">',
  3300 =>'<img src="./images/rank/WildHunter.png">',
  3310 =>'<img src="./images/rank/WildHunter.png">',
  3311 =>'<img src="./images/rank/WildHunter.png">',
  3312 =>'<img src="./images/rank/WildHunter.png">',
  3500 =>'<img src="./images/rank/Mechanic.png">',
  3510 =>'<img src="./images/rank/Mechanic.png">',
  3511 =>'<img src="./images/rank/Mechanic.png">',
  3512 =>'<img src="./images/rank/Mechanic.png">',
  501 =>'<img src="./images/rank/Cannoneer.png">',
  530 =>'<img src="./images/rank/Cannoneer.png">',
  531 =>'<img src="./images/rank/Cannoneer.png">',
  532 =>'<img src="./images/rank/Cannoneer.png">',
  2002 =>'<img src="./images/rank/Mercedes.png">',
  2300 =>'<img src="./images/rank/Mercedes.png">',
  2310 =>'<img src="./images/rank/Mercedes.png">',
  2311 =>'<img src="./images/rank/Mercedes.png">',
  2312 =>'<img src="./images/rank/Mercedes.png">',
  3001 =>'<img src="./images/rank/DemonSlayer.png">',
  3100 =>'<img src="./images/rank/DemonSlayer.png">',
  3110 =>'<img src="./images/rank/DemonSlayer.png">',
  3111 =>'<img src="./images/rank/DemonSlayer.png">',
  3112 =>'<img src="./images/rank/DemonSlayer.png">',
  508 =>'<img src="./images/rank/Jett.png">',
  570 =>'<img src="./images/rank/Jett.png">',
  571 =>'<img src="./images/rank/Jett.png">',
  572 =>'<img src="./images/rank/Jett.png">',
  2003 =>'<img src="./images/rank/Phantom.png">',
  2400 =>'<img src="./images/rank/Phantom.png">',
  2410 =>'<img src="./images/rank/Phantom.png">',
  2411 =>'<img src="./images/rank/Phantom.png">',
  2412 =>'<img src="./images/rank/Phantom.png">',
);

?>
<div align="center">
	<div align="left" class="content">
	<div align="center" class="content-title">Rankings</div>
	<div class="content-border">
	<center>
<br>
<table border='3' bordercolor='#0000000' style='border-style: solid;  border-collapse: collapse' >

<tr >

<th bgcolor='#01b3b3' style='height: 30px;width: 90px;'><font color="#fffff">&nbsp;Rank&nbsp;</font></th>
<th bgcolor='#01b3b3'   style='height: 30px;width: 50px;'><font color="#fffff">&nbsp;&nbsp;</font></th>
<th bgcolor='#01b3b3'   style='height: 30px;width: 110px;'><font color="#fffff">&nbsp;Name&nbsp;</font></th>
<th bgcolor='#01b3b3' style='height: 30px;width: 100px;'><font color="#fffff">&nbsp;Job&nbsp;</font></th>
<th bgcolor='#01b3b3'   style='height: 30px;width: 50px;'><font color="#fffff">&nbsp;Level&nbsp;</font></th>
</tr>
</table>
<table border='3' bordercolor='#0000000' style='border-style: solid;  border-collapse: collapse' >
<?php

$number = 1;
$q = mysql_query('
SELECT characters.name, characters.rank, characters.job , characters.level, characters.fame, characters.level FROM characters, accounts WHERE characters.accountid=accounts.id and characters.gm = 0 and accounts.banned = 0 ORDER BY characters.level DESC LIMIT 10');
while ($r = mysql_fetch_array($q)) {
?><tr>
<font color="#fff">
<td bgcolor='#fafafa'  style='width: 90px; '><center>&nbsp;<?php echo $number; $number = $number+1;?>&nbsp;</center></td>
<td bgcolor='#fafafa' border  style='width: 50px; '><center>&nbsp;<?php echo $job[$r['job']];?>&nbsp;</center></td>
<td bgcolor='#fafafa'  style='width: 110px; '><center>&nbsp;<?php echo $r['name'];?>&nbsp;</center></td>
<td bgcolor='#fafafa'  style='width: 100px; '><center>&nbsp;<?php echo $jobs[$r['job']];?>&nbsp;</center></td>
<td bgcolor='#fafafa'  style='width: 50px;'><center>&nbsp;<?php echo $r['level'];?>&nbsp;</center></b></td>
</font>

</tr>

<?php } ?>
</table>
</center
</div>
</div>
</div>